spring:
  datasource:
    driver: org.postgresql.Driver
    username: root
    password: root
    url: jdbc:postgresql://localhost:5432/root
  application:
    name: tuum

currencies:
  allowed-currencies: EUR, SEK, GBP, USD